-- =============================================================================
-- Migración 0101: NO-OP de seguridad (neutralizada tras incidente en producción)
-- =============================================================================
-- Este archivo se conserva con su nombre original ÚNICAMENTE para el ledger
-- `_migrations`: así el runner lo registra como aplicado y nunca vuelve a
-- intentar ejecutarlo.
--
-- MOTIVO (incidente real):
--   El contenido original aplicaba desplazamientos `DATE_SUB(..., INTERVAL 2 HOUR)`
--   y `DATE_ADD(..., INTERVAL 2 HOUR)` asumiendo que los timestamps estaban en
--   CEST. Pero la conexión PDO fija la sesión a UTC (`PdoFactory`:
--   `SET time_zone = '+00:00'`), por lo que la BD SIEMPRE almacena en UTC.
--   Aplicar esos desplazamientos era incorrecto y corrompía los timestamps.
--
--   Además, el script contenía sentencias SELECT mezcladas con UPDATE. Al
--   ejecutarse con `PDO::exec()` de golpe, MariaDB sí corría los UPDATE pero
--   PDO lanzaba "Cannot execute queries while there are pending result sets";
--   el `catch` impedía registrar la migración, dejándola pendiente y dispuesta
--   a repetirse. Los datos ya fueron reparados manualmente.
--
-- QUÉ HACE AHORA:
--   Nada. Este archivo no contiene ninguna sentencia ejecutable (solo
--   comentarios), por lo que el splitter del Migrator devuelve 0 sentencias:
--   no hay UPDATE ni DDL destructivo posible.
--
-- SI ALGUNA VEZ SE NECESITARA una corrección de timestamps:
--   NO reutilizar este archivo. Crear una migración NUEVA y explícita que:
--     1) Verifique el estado real con SELECT antes de tocar nada.
--     2) Trabaje en UTC (que es el formato real de la BD).
--     3) Sea idempotente y no dependa de suposiciones de zona horaria local.
-- =============================================================================
